const SEARCH_BASE = '/api/steam-search'
const DETAIL_BASE = '/api/steam-detail'

// 常见游戏中英文名对照（Steam 搜索 API 不支持中文查询）
const CN_TO_EN = {
  '星露谷物语': 'stardew valley',
  '艾尔登法环': 'elden ring',
  '塞尔达': 'zelda',
  '荒野大镖客': 'red dead redemption',
  '赛博朋克': 'cyberpunk',
  '巫师3': 'witcher 3',
  '巫师': 'witcher',
  'GTA5': 'grand theft auto v',
  'GTA': 'grand theft auto',
  '我的世界': 'minecraft',
  '怪物猎人': 'monster hunter',
  '生化危机': 'resident evil',
  '最终幻想': 'final fantasy',
  '黑暗之魂': 'dark souls',
  '只狼': 'sekiro',
  '空洞骑士': 'hollow knight',
  '哈迪斯': 'hades',
  '蔚蓝': 'celeste',
  '传说之下': 'undertale',
  '饥荒': 'dont starve',
  '文明': 'civilization',
  '帝国时代': 'age of empires',
  '全面战争': 'total war',
  '英雄无敌': 'heroes of might and magic',
  '暗黑破坏神': 'diablo',
  '守望先锋': 'overwatch',
  '英雄联盟': 'league of legends',
  '反恐精英': 'counter-strike',
  '刀塔': 'dota',
  '绝地求生': 'pubg',
  '堡垒之夜': 'fortnite',
  '原神': 'genshin impact',
  '崩坏': 'honkai',
  '王者荣耀': 'arena of valor',
  '永劫无间': 'naraka bladepoint',
  '黑神话悟空': 'black myth wukong',
  '动物森友会': 'animal crossing',
  '马力欧': 'mario',
  '宝可梦': 'pokemon',
  '口袋妖怪': 'pokemon',
  '精灵宝可梦': 'pokemon',
  '合金装备': 'metal gear solid',
  '潜龙谍影': 'metal gear solid',
  '战神': 'god of war',
  '地平线': 'horizon',
  '对马岛之魂': 'ghost of tsushima',
  '最后生还者': 'the last of us',
  '神秘海域': 'uncharted',
  '血源': 'bloodborne',
  '仁王': 'nioh',
  '卧龙': 'wo long',
  '破晓传说': 'tales of arise',
  '女神异闻录': 'persona',
  '如龙': 'yakuza',
  '马力欧卡丁车': 'mario kart',
  '超级马里奥': 'super mario',
  '塞尔达传说': 'the legend of zelda',
  '异度神剑': 'xenoblade',
  '火焰纹章': 'fire emblem',
  '喷射战士': 'splatoon',
  '斯普拉遁': 'splatoon',
  '健身环': 'ring fit adventure',
  '脑锻炼': 'brain age',
  '集合啦动物森友会': 'animal crossing new horizons',
  '马力欧奥德赛': 'super mario odyssey',
  '塞尔达旷野之息': 'the legend of zelda breath of the wild',
  '塞尔达王国之泪': 'the legend of zelda tears of the kingdom',
  '博德之门': 'baldurs gate',
  '神界原罪': 'divinity original sin',
  '极乐迪斯科': 'disco elysium',
  '杀戮尖塔': 'slay the spire',
  '死亡细胞': 'dead cells',
  '蔚蓝档案': 'celeste',
  '以撒的结合': 'the binding of isaac',
  '挺进地牢': 'enter the gungeon',
  '小丑牌': 'balatro',
  '土豆兄弟': 'brotato',
  '吸血鬼幸存者': 'vampire survivors',
  '潜水员戴夫': 'dave the diver',
  '女神异闻录5': 'persona 5',
  '双人成行': 'it takes two',
  '胡闹厨房': 'overcooked',
  '人类一败涂地': 'human fall flat',
  '糖豆人': 'fall guys',
  '鹅鸭杀': 'goose goose duck',
  'Among Us': 'among us',
  '恐鬼症': 'phasmophobia',
  '致命公司': 'lethal company',
  '幻兽帕鲁': 'palworld',
  '帕鲁': 'palworld',
  '雾锁王国': 'enshrouded',
  '庄园领主': 'manor lords',
  '城市天际线': 'cities skylines',
  '缺氧': 'oxygen not included',
  '异星工厂': 'factorio',
  '戴森球计划': 'dyson sphere program',
  '群星': 'stellaris',
  '十字军之王': 'crusader kings',
  '欧陆风云': 'europa universalis',
  '钢铁雄心': 'hearts of iron',
  '维多利亚': 'victoria',
  '冰汽时代': 'frostpunk',
  '这是我的战争': 'this war of mine',
  '幽灵线东京': 'ghostwire tokyo',
  '死亡搁浅': 'death stranding',
  '合金装备5': 'metal gear solid v',
  '合金装备幻痛': 'metal gear solid v the phantom pain',
  '消逝的光芒': 'dying light',
  '地铁': 'metro',
  '潜行者': 'stalker',
  '切尔诺贝利': 'chernobyl',
  '瘟疫传说': 'a plague tale',
  '控制': 'control',
  '量子破碎': 'quantum break',
  '心灵杀手': 'alan wake',
  '马克思佩恩': 'max payne',
  '正当防卫': 'just cause',
  '看门狗': 'watch dogs',
  '刺客信条': 'assassins creed',
  '孤岛惊魂': 'far cry',
  '彩虹六号': 'rainbow six',
  '幽灵行动': 'ghost recon',
  '全境封锁': 'the division',
  '荣耀战魂': 'for honor',
  '极限国度': 'riders republic',
  '飙酷车神': 'the crew',
  '舞力全开': 'just dance',
  '极限竞速': 'forza',
  '地平线零之曙光': 'horizon zero dawn',
  '地平线西之绝境': 'horizon forbidden west',
  '战神4': 'god of war',
  '战神诸神黄昏': 'god of war ragnarok',
  '对马岛': 'ghost of tsushima',
  '最后生还者2': 'the last of us part ii',
  '最终幻想7': 'final fantasy vii',
  '最终幻想14': 'final fantasy xiv',
  '最终幻想15': 'final fantasy xv',
  '最终幻想16': 'final fantasy xvi',
  '勇者斗恶龙': 'dragon quest',
  '八方旅人': 'octopath traveler',
  '歧路旅人': 'octopath traveler',
  '破晓传说': 'tales of arise',
  '绯红结系': 'scarlet nexus',
  '噬神者': 'god eater',
  '讨鬼传': 'toukiden',
  '无双': 'warriors',
  '真三国无双': 'dynasty warriors',
  '战国无双': 'samurai warriors',
  '海贼无双': 'one piece warriors',
  '塞尔达无双': 'hyrule warriors',
  '火焰纹章风花雪月': 'fire emblem three houses',
  '火焰纹章engage': 'fire emblem engage',
  '马力欧派对': 'mario party',
  '纸片马力欧': 'paper mario',
  '路易吉洋馆': 'luigis mansion',
  '星之卡比': 'kirby',
  '大金刚': 'donkey kong',
  '皮克敏': 'pikmin',
  '密特罗德': 'metroid',
  '银河战士': 'metroid',
  '零之轨迹': 'trails from zero',
  '碧之轨迹': 'trails to azure',
  '闪之轨迹': 'trails of cold steel',
  '伊苏': 'ys',
  '英雄传说': 'the legend of heroes',
  '轨迹': 'trails',
  '炼金工房': 'atelier',
  '莱莎的炼金工房': 'atelier ryza',
  '薄暮传说': 'tales of vesperia',
  '狂战传说': 'tales of berseria',
  '宵星传说': 'tales of vesperia',
  '深渊传说': 'tales of the abyss',
  '仙乐传说': 'tales of symphonia',
  '破晓传说': 'tales of arise',
  '女神异闻录4': 'persona 4',
  '女神异闻录3': 'persona 3',
  '真女神转生': 'shin megami tensei',
  '世界树迷宫': 'etrian odyssey',
  '勇者斗恶龙11': 'dragon quest xi',
  '八方旅人2': 'octopath traveler ii',
  '三角战略': 'triangle strategy',
  '皇家骑士团': 'tactics ogre',
  '最终幻想战略版': 'final fantasy tactics',
  '火焰纹章结合': 'fire emblem engage',
  '马力欧RPG': 'mario rpg',
  '纸片马力欧折纸王国': 'paper mario the origami king',
  '路易吉洋馆3': 'luigis mansion 3',
  '超级马里奥惊奇': 'super mario bros wonder',
  '马力欧惊奇': 'super mario bros wonder',
  '塞尔达智慧的再现': 'the legend of zelda echoes of wisdom',
  '马力欧vs大金刚': 'mario vs donkey kong',
  '桃花公主': 'princess peach showtime',
  '碧琪公主': 'princess peach showtime',
  '超级舞动瓦力欧制造': 'wario ware move it',
  '斯普拉遁3': 'splatoon 3',
  '宝可梦朱紫': 'pokemon scarlet violet',
  '宝可梦朱': 'pokemon scarlet',
  '宝可梦紫': 'pokemon violet',
  '宝可梦阿尔宙斯': 'pokemon legends arceus',
  '宝可梦传说阿尔宙斯': 'pokemon legends arceus',
  '宝可梦晶灿钻石': 'pokemon brilliant diamond',
  '宝可梦明亮珍珠': 'pokemon shining pearl',
  '宝可梦剑盾': 'pokemon sword shield',
  '宝可梦剑': 'pokemon sword',
  '宝可梦盾': 'pokemon shield',
  '宝可梦日月': 'pokemon sun moon',
  '宝可梦究极日月': 'pokemon ultra sun ultra moon',
  '健身环大冒险': 'ring fit adventure',
  '脑锻炼': 'brain age',
  '任天堂明星大乱斗': 'super smash bros',
  '大乱斗': 'super smash bros',
  '马力欧赛车8': 'mario kart 8',
  '马车8': 'mario kart 8',
  '底特律变人': 'detroit become human',
  '底特律化身为人': 'detroit become human',
  '底特律': 'detroit become human',
  '暴雨': 'heavy rain',
  '超凡双生': 'beyond two souls',
  '奇异人生': 'life is strange',
  '直到黎明': 'until dawn',
  '黑相集': 'the dark pictures',
  '小小梦魇': 'little nightmares',
  'inside': 'inside',
  'limbo': 'limbo',
  '地狱之刃': 'hellblade',
  '地狱之刃塞娜的献祭': 'hellblade senuas sacrifice',
  '奥日': 'ori',
  '奥日与黑暗森林': 'ori and the blind forest',
  '奥日与鬼火意志': 'ori and the will of the wisps',
  '光明记忆': 'bright memory',
  '鬼谷八荒': 'tale of immortal',
  '了不起的修仙模拟器': 'amazing cultivation simulator',
  '太吾绘卷': 'the scroll of taiwu',
  '觅长生': 'seek longevity',
  '部落与弯刀': 'sands of salzaar',
  '枪火重生': 'gunfire reborn',
  '戴森球计划': 'dyson sphere program',
  '暗影火炬城': 'f.i.s.t.',
  '仙剑奇侠传': 'chinese paladin',
  '古剑奇谭': 'ancient chinese paladin',
  '轩辕剑': 'xuanyuan sword',
  '侠客风云传': 'tale of wuxia',
  '天命奇御': 'fate seeker',
  '侠之道': 'path of wuxia',
  '嗜血印': 'bloody spell',
  '斩妖行': 'the wandering blade',
  '只狼影逝二度': 'sekiro shadows die twice',
  '只狼': 'sekiro',
  '黑暗之魂3': 'dark souls iii',
  '黑暗之魂2': 'dark souls ii',
  '黑暗之魂1': 'dark souls',
  '恶魔之魂': 'demons souls',
  '血源诅咒': 'bloodborne',
  '仁王2': 'nioh 2',
  '仁王': 'nioh',
  '卧龙苍天陨落': 'wo long fallen dynasty',
  '卧龙': 'wo long',
  '对马岛之魂': 'ghost of tsushima',
  '浪人崛起': 'rise of the ronin',
  '星之海': 'sea of stars',
  '信使': 'the messenger',
  '空洞骑士丝之歌': 'hollow knight silksong',
  '蔚蓝': 'celeste',
  '蔚蓝档案': 'celeste archive',
  '传说之下': 'undertale',
  '三角符文': 'deltarune',
  '极乐迪斯科': 'disco elysium',
  '极乐迪斯科最终剪辑版': 'disco elysium the final cut',
  '杀戮尖塔': 'slay the spire',
  '杀戮尖塔2': 'slay the spire 2',
  '死亡细胞': 'dead cells',
  '以撒的结合': 'the binding of isaac',
  '以撒的结合重生': 'the binding of isaac rebirth',
  '挺进地牢': 'enter the gungeon',
  '小丑牌': 'balatro',
  '土豆兄弟': 'brotato',
  '吸血鬼幸存者': 'vampire survivors',
  '潜水员戴夫': 'dave the diver',
  '哈迪斯': 'hades',
  '哈迪斯2': 'hades ii',
  '黑帝斯': 'hades',
  '节奏医生': 'rhythm doctor',
  '喵斯快跑': 'muse dash',
  '胡闹厨房': 'overcooked',
  '胡闹厨房2': 'overcooked 2',
  '分手厨房': 'overcooked',
  '双人成行': 'it takes two',
  '逃出生天': 'a way out',
  '人类一败涂地': 'human fall flat',
  '糖豆人': 'fall guys',
  '鹅鸭杀': 'goose goose duck',
  '恐鬼症': 'phasmophobia',
  '致命公司': 'lethal company',
  '幻兽帕鲁': 'palworld',
  '帕鲁': 'palworld',
  '雾锁王国': 'enshrouded',
  '庄园领主': 'manor lords',
  '城市天际线': 'cities skylines',
  '城市天际线2': 'cities skylines ii',
  '缺氧': 'oxygen not included',
  '异星工厂': 'factorio',
  '群星': 'stellaris',
  '十字军之王3': 'crusader kings iii',
  '欧陆风云4': 'europa universalis iv',
  '钢铁雄心4': 'hearts of iron iv',
  '维多利亚3': 'victoria 3',
  '冰汽时代': 'frostpunk',
  '冰汽时代2': 'frostpunk 2',
  '这是我的战争': 'this war of mine',
  '幽灵线东京': 'ghostwire tokyo',
  '死亡搁浅': 'death stranding',
  '死亡搁浅导演剪辑版': 'death stranding directors cut',
  '合金装备5幻痛': 'metal gear solid v the phantom pain',
  '潜龙谍影5': 'metal gear solid v',
  '消逝的光芒': 'dying light',
  '消逝的光芒2': 'dying light 2',
  '地铁离去': 'metro exodus',
  '地铁2033': 'metro 2033',
  '地铁最后的曙光': 'metro last light',
  '潜行者': 'stalker',
  '潜行者2': 'stalker 2',
  '瘟疫传说无罪': 'a plague tale innocence',
  '瘟疫传说安魂曲': 'a plague tale requiem',
  '控制': 'control',
  '心灵杀手2': 'alan wake 2',
  '心灵杀手': 'alan wake',
  '量子破碎': 'quantum break',
  '正当防卫': 'just cause',
  '看门狗': 'watch dogs',
  '刺客信条': 'assassins creed',
  '孤岛惊魂': 'far cry',
  '彩虹六号': 'rainbow six',
  '幽灵行动': 'ghost recon',
  '全境封锁': 'the division',
  '荣耀战魂': 'for honor',
  '极限国度': 'riders republic',
  '极限竞速': 'forza',
  '地平线零之曙光': 'horizon zero dawn',
  '地平线西之绝境': 'horizon forbidden west',
  '战神4': 'god of war',
  '战神诸神黄昏': 'god of war ragnarok',
  '最后生还者': 'the last of us',
  '最后生还者2': 'the last of us part ii',
  '神秘海域': 'uncharted',
  '最终幻想7重制版': 'final fantasy vii remake',
  '最终幻想14': 'final fantasy xiv',
  '最终幻想15': 'final fantasy xv',
  '最终幻想16': 'final fantasy xvi',
  '勇者斗恶龙': 'dragon quest',
  '八方旅人': 'octopath traveler',
  '歧路旅人': 'octopath traveler',
  '博德之门3': 'baldurs gate 3',
  '博德之门': 'baldurs gate',
  '神界原罪': 'divinity original sin',
  '神界原罪2': 'divinity original sin 2',
  '永恒之柱': 'pillars of eternity',
  '开拓者': 'pathfinder',
  '拥王者': 'pathfinder kingmaker',
  '正义之怒': 'pathfinder wrath of the righteous',
  '龙腾世纪': 'dragon age',
  '质量效应': 'mass effect',
  '辐射': 'fallout',
  '上古卷轴': 'the elder scrolls',
  '天际': 'skyrim',
  '天际特别版': 'the elder scrolls v skyrim',
  '星空': 'starfield',
  '辐射4': 'fallout 4',
  '辐射76': 'fallout 76',
  '辐射新维加斯': 'fallout new vegas',
  '赛博朋克2077': 'cyberpunk 2077',
  '赛博朋克': 'cyberpunk 2077',
  '巫师3': 'the witcher 3',
  '巫师': 'the witcher',
  '荒野大镖客2': 'red dead redemption 2',
  '荒野大镖客': 'red dead redemption',
  'GTA5': 'grand theft auto v',
  'GTA6': 'grand theft auto vi',
  'GTA': 'grand theft auto',
  '三男一狗': 'grand theft auto v',
  '给他爱': 'grand theft auto',
  '艾尔登法环': 'elden ring',
  '黑暗之魂': 'dark souls',
  '只狼': 'sekiro',
  '怪物猎人': 'monster hunter',
  '怪物猎人世界': 'monster hunter world',
  '怪物猎人崛起': 'monster hunter rise',
  '怪物猎人荒野': 'monster hunter wilds',
  '生化危机': 'resident evil',
  '生化危机4': 'resident evil 4',
  '生化危机8': 'resident evil village',
  '鬼泣': 'devil may cry',
  '鬼泣5': 'devil may cry 5',
  '街霸': 'street fighter',
  '街头霸王': 'street fighter',
  '街霸6': 'street fighter 6',
  '铁拳': 'tekken',
  '拳皇': 'king of fighters',
  '侍魂': 'samurai shodown',
  '罪恶装备': 'guilty gear',
  '苍翼默示录': 'blazblue',
  '龙珠': 'dragon ball',
  '火影忍者': 'naruto',
  '海贼王': 'one piece',
  '龙珠斗士z': 'dragon ball fighterz',
  '龙珠超宇宙': 'dragon ball xenoverse',
  '火影忍者究极风暴': 'naruto shippuden ultimate ninja storm',
  '海贼无双': 'one piece warriors',
  '真三国无双': 'dynasty warriors',
  '战国无双': 'samurai warriors',
  '无双': 'warriors',
  '塞尔达无双': 'hyrule warriors',
  '火焰纹章': 'fire emblem',
  '火焰纹章风花雪月': 'fire emblem three houses',
  '火焰纹章engage': 'fire emblem engage',
  '异度神剑': 'xenoblade',
  '异度神剑3': 'xenoblade chronicles 3',
  '女神异闻录': 'persona',
  '女神异闻录5': 'persona 5',
  '女神异闻录4': 'persona 4',
  '女神异闻录3': 'persona 3',
  '真女神转生': 'shin megami tensei',
  '真女神转生5': 'shin megami tensei v',
  '如龙': 'yakuza',
  '如龙0': 'yakuza 0',
  '如龙极': 'yakuza kiwami',
  '如龙极2': 'yakuza kiwami 2',
  '如龙7': 'yakuza like a dragon',
  '如龙8': 'like a dragon infinite wealth',
  '审判之眼': 'judgment',
  '审判之逝': 'lost judgment',
  '破晓传说': 'tales of arise',
  '绯红结系': 'scarlet nexus',
  '噬神者': 'god eater',
  '讨鬼传': 'toukiden',
  '轨迹': 'trails',
  '空之轨迹': 'trails in the sky',
  '零之轨迹': 'trails from zero',
  '碧之轨迹': 'trails to azure',
  '闪之轨迹': 'trails of cold steel',
  '黎之轨迹': 'trails through daybreak',
  '伊苏': 'ys',
  '英雄传说': 'the legend of heroes',
  '炼金工房': 'atelier',
  '莱莎的炼金工房': 'atelier ryza',
  '莱莎': 'atelier ryza',
  '勇者斗恶龙11': 'dragon quest xi',
  '八方旅人2': 'octopath traveler ii',
  '三角战略': 'triangle strategy',
  '皇家骑士团': 'tactics ogre',
  '最终幻想战略版': 'final fantasy tactics',
  '马力欧派对': 'mario party',
  '纸片马力欧': 'paper mario',
  '路易吉洋馆': 'luigis mansion',
  '星之卡比': 'kirby',
  '大金刚': 'donkey kong',
  '皮克敏': 'pikmin',
  '密特罗德': 'metroid',
  '银河战士': 'metroid',
  '密特罗德生存恐惧': 'metroid dread',
  '马力欧奥德赛': 'super mario odyssey',
  '超级马里奥奥德赛': 'super mario odyssey',
  '塞尔达旷野之息': 'the legend of zelda breath of the wild',
  '塞尔达王国之泪': 'the legend of zelda tears of the kingdom',
  '塞尔达智慧的再现': 'the legend of zelda echoes of wisdom',
  '马力欧惊奇': 'super mario bros wonder',
  '超级马里奥惊奇': 'super mario bros wonder',
  '马力欧赛车8': 'mario kart 8',
  '马车8': 'mario kart 8',
  '任天堂明星大乱斗': 'super smash bros',
  '大乱斗': 'super smash bros',
  '斯普拉遁3': 'splatoon 3',
  '喷射战士': 'splatoon',
  '宝可梦朱紫': 'pokemon scarlet violet',
  '宝可梦朱': 'pokemon scarlet',
  '宝可梦紫': 'pokemon violet',
  '宝可梦阿尔宙斯': 'pokemon legends arceus',
  '宝可梦传说阿尔宙斯': 'pokemon legends arceus',
  '宝可梦剑盾': 'pokemon sword shield',
  '健身环大冒险': 'ring fit adventure',
  '健身环': 'ring fit adventure',
}

export async function searchGames(query) {
  try {
    // 先尝试中文名映射
    let searchTerm = query.trim()
    const mapped = CN_TO_EN[searchTerm]
    if (mapped) searchTerm = mapped

    const res = await fetch(`${SEARCH_BASE}/?term=${encodeURIComponent(searchTerm)}&l=schinese&cc=CN`)
    if (!res.ok) return []

    const data = await res.json()
    const items = data.items || []
    return items.map(g => {
      const platformNames = []
      if (g.platforms) {
        if (g.platforms.windows) platformNames.push('Windows')
        if (g.platforms.mac) platformNames.push('Mac')
        if (g.platforms.linux) platformNames.push('Linux')
      }
      return {
        id: g.id,
        steamAppID: String(g.id),
        name: g.name || '',
        image: g.tiny_image || `https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/${g.id}/header.jpg`,
        genres: [],
        platforms: platformNames,
      }
    })
  } catch (e) {
    console.warn('游戏搜索失败:', e)
    return []
  }
}

export async function getGameDetails(gameId) {
  try {
    const res = await fetch(`${DETAIL_BASE}/?appids=${gameId}&l=schinese&cc=CN`)
    if (!res.ok) return null

    const data = await res.json()
    const app = data[gameId]
    if (!app?.success) return null

    const info = app.data || {}
    return {
      id: gameId,
      name: info.name || '',
      steamAppID: String(gameId),
      image: info.header_image || `https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/${gameId}/header.jpg`,
      developers: info.developers || [],
      publishers: info.publishers || [],
      genres: (info.genres || []).map(g => g.description).filter(Boolean),
      releaseDate: info.release_date?.date || '',
      shortDescription: info.short_description || '',
    }
  } catch (e) {
    console.warn('游戏详情获取失败:', e)
    return null
  }
}
